# Vectors
A vector is a list of numbers in order, commonly referred to as components or elements. They are different features of points of data expressed in an ordered form. A vector in a two-dimensional plane can be defined as:

ν= (x1, x2)

#### Scalars, Vectors and Matrices
Scalars: Any single value from our dataset would represent a scalar like integers or floating-point numbers, employed in mathematical computation.
Vectors: Vectors are one-dimensional number arrays that hold several values in a linear sequence.
Matrices: Matrices are two-dimensional arrays of multiple vectors that are placed in rows and columns.

#### Vectors in Machine Learning Models
Vectors are used at various points in machine learning models:

1. Input: Machines only process data numerically. The inputs like images, text or sensor inputs must be converted into numbers and represented as vectors. Models are able to efficiently analyze data by this organized representation. Feature engineering methods assist in converting raw data into useful vector representations for training models.

2. Model: The heart of machine learning is creating models that take in input data and learn to make predictions. In deep learning models, this is done through a neural network wherein the layers of the neural network employ linear algebra (such as matrix and vector multiplication) in order to update your parameters. Vectors can be used for operations like scaling, rotation and reducing dimensions, which allows computations to be efficient and increase model accuracy.

3. Outputs: The results of machine learning models can take various forms, such as numbers, images or even vectors. f we’re classifying images, the output will be a category of image. For instance, in natural language processing (NLP), a vector may represent the final output of a model and serve as input for another task, such as classification or recommendation systems. Vector operations such as similarity calculations, clustering and projections are used to interpret and refine model outputs.

Types of Vectors in Machine Learning
1. Row and Column Vectors
A row vector is a one-dimensional array represented in a row format: (x1, x2, x3)
A column vector is a one-dimensional array represented in a column notation:

2. Zero Vector
A vector with all elements as zero. Example:


Zero vectors are useful when solving optimization problems and are the origin in vector space.

3. Unit Vector
A vector of magnitude 1. It is frequently used to denote direction:


4. Sparse and Dense Vectors
Sparse Vectors consist primarily of zeros and are employed in text analysis and recommendation systems.
Dense Vectors consist primarily of non-zero values and are employed in image processing and deep learning.
Importance of Vectors in Machine Learning
1. Feature Representation
Vectors are used to represent data points in numerical form. For example, in natural language processing (NLP), words are translated into word vectors by techniques such as Word2Vec or TF-IDF.

2. Distance and Similarity Measures
Similarity between data points is typically calculated in machine learning by vector distance measures like:

Euclidean Distance: Quantitative measure of straight-line distance between two points.
Cosine Similarity: Quantifies the cosine of the angle between two vectors to ascertain similarity.
3. Transformations and Projections
Vectors enable mathematical transformations such as rotation, scaling and translation. These are employed in methods such as Principal Component Analysis (PCA) to project datasets into lower dimensions.

3. Transformations and Projections
Vectors enable mathematical transformations such as rotation, scaling and translation. These are employed in methods such as Principal Component Analysis (PCA) to project datasets into lower dimensions.



### Vector Operations


In [11]:
# 1. Vector Addition and Subtraction
import numpy as np
a = np.array([3,4])
b = np.array([5,9])


add = a + b

sub = a - b

print("Addition:", add)

print("Subtraction:", sub)

# Scalar multiplication

scalar = 4

scalar_multiple = a * scalar

print("scalar Result:", scalar_multiple)


# Dot Product


dot_prod = np.dot(a,b)
print("Dot Product:", dot_prod)

# cross product
c = np.array([1,2,4])
d = np.asarray([4,5,6])

cross_prod = np.cross(c,d)

print("Cross Product:", cross_prod)

# Magnitude (L2 Normalization / Eucledian Length)

magnitude_a = np.linalg.norm(a)
magnitude_b = np.linalg.norm(b)
print("Magnitude of Vector a:", magnitude_a)
print("Magnitude of Vector b:", magnitude_b)

# Unit Vector

unit_vec_a = np.linalg.norm((a/magnitude_a))
unit_vec_b = np.linalg.norm((b/magnitude_b))
print("Unit Vector of a:", unit_vec_a)
print("Unit Vector of b:", unit_vec_b)


Addition: [ 8 13]
Subtraction: [-2 -5]
scalar Result: [12 16]
Dot Product: 51
Cross Product: [-8 10 -3]
Magnitude of Vector a: 5.0
Magnitude of Vector b: 10.295630140987
Unit Vector of a: 1.0
Unit Vector of b: 0.9999999999999999


####
 **Cross product vs. dot product**
- When we compare the dot product and the cross product, there are three main differences.
- The dot product returns a number, but the cross product returns a vector.
- The dot product works in any number of dimensions, but the cross product only works in 3D.
- The dot product measures how much two vectors point in the same direction, but the cross product measures how much two vectors point in different directions.

#### Application of Vectors in Machine Learning
Vectors play a crucial role in various machine learning algorithms and natural language processing (NLP) techniques.

- Linear Regression- Linear regression employs vectors to denote the independent and dependent variable relationship: Y = Xw + b where X is a feature vector, w is a weights vector and b is the bias term.
- Support Vector Machines (SVMs)- SVMs utilize vector mathematics to identify the best hyperplane separating various classes in classification problems.
- Neural Networks- Neural networks store weights, activations and gradients as vectors, making them crucial for deep learning models.
- Clustering (K-Means Algorithm)- The K-Means algorithm allocates points to clusters based on vector distances.
Word Embeddings in NLP- Methods such as Word2Vec and GloVe map words to vectors, capturing their semantic meaning.
Sentence and Document Embeddings- Sentences and documents can also be encoded as vectors using techniques like BERT and Doc2Vec

### Matrices
What is a Matrix?
A matrix is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns.

Dimensions: A matrix is defined by its number of rows (m) and columns (n). We refer to an m
timesn matrix.

Elements: Each number within the matrix is called an element. An element at the i-th row and j-th column is typically denoted as A_ij or a_ij.

In [22]:
# creating a 2X3 matrix

matrix_A = np.array([[1,2,3], [4,5,6]])

print(f"Matrix A shape: {matrix_A.shape}")


# 3X2
matrix_B = np.array([[7,8],[9,10],[11,12]])
print(f"Matrix B shape: {matrix_B.shape}")

matrix_C = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(f"Matrix B shape: {matrix_C}")


#Transposition

matrix_A_T = matrix_A.T

# alternative
matrix_A_T_alt = np.transpose(matrix_A)
print("Matrix A transpose", matrix_A_T_alt)

# Matrix Multiplication
Product_AB = matrix_A @ matrix_B

print("Matrix PRoduct", Product_AB)

# alt

print("Matrix DOT product", np.dot(matrix_A, matrix_B))


# Matrix Inverse
#Must be a square matrix and non-singula

square_matrix_E = np.array([
    [4,7],
    [2,7]
])

print(f"\nSquare matrix E:\n{square_matrix_E}")

inverse_E = np.linalg.inv(square_matrix_E)

print(f"\nSquare matrix E Inverse:\n{inverse_E}")

# Verify identity: Identity states that a dot product of a matrix and its inverse is 1.
identity_E = square_matrix_E @ inverse_E

print("Indentity E", identity_E)



Matrix A shape: (2, 3)
Matrix B shape: (3, 2)
Matrix B shape: [[10 20 30]
 [40 50 60]]
Matrix A transpose [[1 4]
 [2 5]
 [3 6]]
Matrix PRoduct [[ 58  64]
 [139 154]]
Matrix DOT product [[ 58  64]
 [139 154]]

Square matrix E:
[[4 7]
 [2 7]]

Square matrix E Inverse:
[[ 0.5        -0.5       ]
 [-0.14285714  0.28571429]]
Indentity E [[ 1.00000000e+00 -1.11022302e-16]
 [ 5.55111512e-17  1.00000000e+00]]


### Eigen Value & Eigen Vectors
Eigenvalues and Eigenvectors (often called "eigen-things" from German, meaning "self" or "characteristic") are special values and vectors that reveal intrinsic properties of linear transformations represented by matrices.








In [26]:
# Example
# A 2X2 Matrix
import numpy as np

matrix_A = np.array([
    [4,-2],
    [1,1]
])
print(f"Original Matrix A:\n{matrix_A}")

eigvals, eigvecs = np.linalg.eig(matrix_A)

print(f"\nEigenvalues (λ): {eigvals}")
print(f"Eigenvectors (columns correspond to eigenvalues):\n{eigvecs}")


# Let's verify for the first eigenvalue and eigenvector
# A * v = lambda * v
print("\n--- Verification for first Eigenvalue/Eigenvector ---")
lambda_1 = eigvals[0]
v_1 = eigvecs[:, 0] # First column is the first eigenvector

print(f"First Eigenvalue (λ1): {lambda_1}")
print(f"First Eigenvector (v1): {v_1}")

# Calculate A * v1
Av1 = matrix_A @ v_1
print(f"A * v1: {Av1}")

# Calculate lambda1 * v1
lambda_v1 = lambda_1 * v_1
print(f"λ1 * v1: {lambda_v1}")


Original Matrix A:
[[ 4 -2]
 [ 1  1]]

Eigenvalues (λ): [3. 2.]
Eigenvectors (columns correspond to eigenvalues):
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]

--- Verification for first Eigenvalue/Eigenvector ---
First Eigenvalue (λ1): 3.0
First Eigenvector (v1): [0.89442719 0.4472136 ]
A * v1: [2.68328157 1.34164079]
λ1 * v1: [2.68328157 1.34164079]
