## Numpy

Numpy (Numerical Python) is a foundational library for scientific computing in Python. It provides a high performance multi-dimentional array object, and tools for working with these objects. Numpy Arrays are more efficient than Python lists (50X faster) for numerical operations especialy in large datasets, because they are densely packed in memory (NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently - aka locality of reference) and leverage optimixed C code.



In [4]:
import numpy as np

In [5]:
mylist = [1,3,45,6]

myarr = np.array(mylist)

type(myarr)

numpy.ndarray

In [8]:
shape = (2,4)

ones_Arr = np.ones(shape)
zeros_Arr = np.zeros(shape)
ones_Arr
zeros_Arr

# using range to create array
# Create an array from 0 to 9
range_array = np.arange(10)
print("\nArray from arange(10):", range_array)

# high dim arrays




Array from arange(10): [0 1 2 3 4 5 6 7 8 9]


array([[[[[ 1,  3, 45,  6]]]]])

In [42]:
#slicing 1D Arrays

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

print(arr[-4:])





[5 6]
[4 5 6 7]


In [65]:
#Slice 2D Array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1,1:4])

print(arr[0:2, 2]) # return index 2 on both 

# array data type

print(arr.dtype)

# Creating Arrays With a Defined Data Type

arr = np.array([1,2,3,45], dtype='O')
print(arr)
print(arr.dtype)

# Converting Data Type on Existing Arrays

new_integer_array = arr.astype('i')
print(f"Array: {new_integer_array} is of type: {new_integer_array.dtype}")

[7 8 9]
[3 8]
int64
[1 2 3 45]
object
Array: [ 1  2  3 45] is of type: int32


In [101]:

arr = np.array([[1, 2, 3, 4],[1, 2, 3, 4]])

print(arr)
print('shape of array :', arr.size)

# reshape
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(4, -1))

# Flattening the arrays

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(f"Fllat array: {newarr}")

# iterating arrays
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
flat_arr = list()
for x in arr:
  for y in x:
    for z in y:
      flat_arr.append(z)
print(f"Flat list{flat_arr}")

# Iterate using nditer

for x in np.nditer(arr):
  print(x)


# using enumerate
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)



[[1 2 3 4]
 [1 2 3 4]]
shape of array : 8
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Fllat array: [1 2 3 4 5 6]
Flat list[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
1
2
3
4
5
6
7
8
9
10
11
12
(0,) 1
(1,) 2
(2,) 3


In [121]:
# join two arrays using concatenate
# axis=1 is for rows wise , axis = 0 for column wise addition


arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(f"Concatenate:{arr}")

# using stack
# Stacking is same as concatenation, the only difference is that stacking is done along a new axis.


arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

# Stacking Along Rows
# NumPy provides a helper function: hstack() to stack along rows.

arr = np.hstack((arr1,arr2))
print(f"hstacked:{arr}")

split_ar = np.array_split(arr,4)
print(f"split arr:{split_ar}")

# Search arrays
# To search an array, use the where() method.


arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x) #returns a tule of index positions where array element is 4

x = np.where(arr%2==0)
print(f"Even indexes: {x}")

# Filter Array
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

# filter odd numbers onlt

numbers = np.array([1,2,3,4,5,6,7,8,9,10])

filters = []

lambda_func = lambda x: True if x%2==1 else False

od_array =list(map(lambda_func, numbers))

for i in numbers:
    if i%2 == 1:
        filters.append(True)
    else:
        filters.append(False)

# now odd array
odd_arr = numbers[filters]

print(f"Odd numbers array: {numbers[od_array]}")


Concatenate:[[1 2 5 6]
 [3 4 7 8]]
[[1 4]
 [2 5]
 [3 6]]
hstacked:[1 2 3 4 5 6]
split arr:[array([1, 2]), array([3, 4]), array([5]), array([6])]
(array([3, 5, 6]),)
Even indexes: (array([1, 3, 5, 6]),)
[41 43]
Odd numbers array: [1 3 5 7 9]
